# Generated by Django 5.2.5 on 2025-08-27 02:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62a9c008-99f4-4fa6-aab0-65b5d236050c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('62a9c008-99f4-4fa6-aab0-65b5d236050c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
