# Generated by Django 5.2.5 on 2025-09-05 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bc65291-68f2-44c4-88d7-68c119aacd79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2bc65291-68f2-44c4-88d7-68c119aacd79'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
