# Generated by Django 5.2.5 on 2025-09-05 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ef63c68-1b7d-4bf6-aa6e-d60228836b14'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ef63c68-1b7d-4bf6-aa6e-d60228836b14'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
