# Generated by Django 5.2.5 on 2025-09-05 04:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1843a14-6d55-41c2-bfeb-c21d05140a0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1843a14-6d55-41c2-bfeb-c21d05140a0c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
