# Generated by Django 5.2.5 on 2025-09-06 02:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ce4a2a6-2084-4daa-a92a-c367039175ce'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ce4a2a6-2084-4daa-a92a-c367039175ce'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
