# Generated by Django 5.2.5 on 2025-09-06 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be385e11-ccc3-4bc7-a8a9-e43ddedfc6e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('be385e11-ccc3-4bc7-a8a9-e43ddedfc6e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
