# Generated by Django 5.2.5 on 2025-09-06 02:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9def5170-be3a-4893-acd7-b131e25321df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9def5170-be3a-4893-acd7-b131e25321df'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
