# Generated by Django 5.2.5 on 2025-09-06 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99d1bfcf-bfb5-4892-982f-9c5d6c7b3369'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99d1bfcf-bfb5-4892-982f-9c5d6c7b3369'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
