# Generated by Django 5.2.5 on 2025-09-06 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_codeverified_id_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('31cdf5e4-180c-41e6-a5f3-c58c822a9bbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('31cdf5e4-180c-41e6-a5f3-c58c822a9bbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
