# Generated by Django 5.2.5 on 2025-09-06 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_codeverified_id_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40c1e638-7787-411d-acea-303e9910b703'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('40c1e638-7787-411d-acea-303e9910b703'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
