# Generated by Django 5.2.5 on 2025-09-06 03:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b338cab4-1dd6-42a9-aac0-5edb1fa2a94f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b338cab4-1dd6-42a9-aac0-5edb1fa2a94f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
