# Generated by Django 5.2.5 on 2025-09-06 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_codeverified_id_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94183a42-e251-4c5a-8bdd-34e2b501d362'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94183a42-e251-4c5a-8bdd-34e2b501d362'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
