# Generated by Django 5.2.5 on 2025-09-06 04:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_phone_nuber_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fcfda716-403a-4c5f-8179-1368101bab0f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fcfda716-403a-4c5f-8179-1368101bab0f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
