# Generated by Django 5.2.5 on 2025-09-06 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2185bb76-a154-4fd9-9ac8-5c9d8b2528e2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2185bb76-a154-4fd9-9ac8-5c9d8b2528e2'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
