# Generated by Django 5.2.5 on 2025-09-06 04:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce5d945c-fe34-4395-91d8-1f61aa37f68f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ce5d945c-fe34-4395-91d8-1f61aa37f68f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
