# Generated by Django 5.2.5 on 2025-09-06 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('509e0728-e31e-444a-8fde-984f46a49cc3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('509e0728-e31e-444a-8fde-984f46a49cc3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
