# Generated by Django 5.2.5 on 2025-09-07 14:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_codeverified_id_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('315983d4-ddff-4acf-87ce-cf816cfbc128'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('315983d4-ddff-4acf-87ce-cf816cfbc128'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
