# Generated by Django 5.2.5 on 2025-09-08 01:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f339d033-c699-4fa6-8465-d7cd360848b8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f339d033-c699-4fa6-8465-d7cd360848b8'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
