# Generated by Django 5.2.5 on 2025-09-09 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d087bd81-0759-4562-bd26-8bc0ca3eac5a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d087bd81-0759-4562-bd26-8bc0ca3eac5a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
