# Generated by Django 5.2.5 on 2025-09-14 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_codeverified_id_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverified',
            name='id',
            field=models.UUIDField(default=uuid.UUID('489e57a6-139f-490c-ba58-7b2853de7c18'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('489e57a6-139f-490c-ba58-7b2853de7c18'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
